### PR TITLE
Update GDrive JS

### PR DESCRIPTION
**Pull request by Hemant-Mann**

### CODE REVIEW

**Comment by PVince81** [comment]
so does GDrive oauth work again with this ? :-D

**Comment by PVince81** [comment]
Nope, doesn't work.

Well, I'm getting 422 "Unprocessable entity" when saving the config.

But I trust that this PR makes us closer to the goal anyway, merging.

**Comment by PVince81** [comment]
same problem on this repo's master

**Comment by Hemant-Mann** [comment]
Okay so this problem of **422 "Unprocessable entity"** is tackled by PR #6 right?

**Comment by PVince81** [comment]
yes it is. Sorry for the comment flood.

**Pull request merged**
